name: buy_and_earn_app
description: A fully functional mobile application for Buy and Earn website.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.7
  google_sign_in: ^6.1.4
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  http: ^1.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  lottie: ^2.6.0
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.2
  flutter_local_notifications: ^15.1.0+1
  google_fonts: ^5.1.0
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  carousel_slider: ^4.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  confetti: ^0.7.0
  flutter_countdown_timer: ^4.1.0
  flutter_native_splash: ^2.3.2
  introduction_screen: ^3.1.11
  pin_code_fields: ^8.0.1
  flutter_launcher_icons: ^0.13.1
  in_app_review: ^2.0.6
  share_plus: ^7.1.0
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  connectivity_plus: ^4.0.2
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.2.0+1
  google_mobile_ads: ^3.0.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

flutter_native_splash:
  color: "#4E54C8"
  image: assets/images/splash_logo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#4E54C8"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png" 